mqtt:
  server: tcp://127.0.0.1:1883
#  server: tcp://192.168.2.69:1883
  username: ""
  password: ""
  certification: ""
configmap: /opt/kubeedge/deviceProfile.json
metaserver:
  enable: true
  addr: http://192.168.2.69:10550
  namespace: dec-public
#  node: zlmap-69f6ffb69f
http_server:
  host: 127.0.0.1:10555
grpc_server:
  socket_path: /tmp/a.sock
common:
  name: mapper-test
  version: v1.0.0
  api_version: v1.0.0
  protocol: modbus
  address: 127.0.0.1
  edgecore_sock: /tmp/edgecore.sock